name: Test

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run TypeScript check
        working-directory: ./app
        run: npm run typecheck

      - name: Run linter
        working-directory: ./app
        run: npm run lint

      - name: Run unit tests
        working-directory: ./app
        run: npm test -- --run

      - name: Run build
        working-directory: ./app
        run: npm run build

      - name: Upload coverage to Codecov (optional)
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        with:
          files: ./app/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./app
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        working-directory: ./app
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 7
